name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - labeled
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'CI start')
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Install Deno
      run: |
        echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV
    - uses: denolib/setup-deno@master
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - name: Run Tests
      run: make test