name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - labeled
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'CI start')
    runs-on: ubuntu-latest
    steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - uses: denolib/setup-deno@master
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - name: Run Tests
      run: make test